name: rakhsaani
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+14

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  path: ^1.9.0
  bot_toast: ^4.1.3
  http: ^1.2.1
  dartz: ^0.10.1
  logger: ^2.1.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  duration: ^3.0.13
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.5
  audioplayers: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Optima
      fonts:
        - asset: assets/fonts/optima.ttf
          weight: 700
    - family: Resagnicto
      fonts:
        - asset: assets/fonts/resagnicto.ttf
          weight: 700
    - family: Noor
      fonts:
        - asset: assets/fonts/noor-regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
